local Object = require("Mods.TheBoxTable.constants.Object")
local Table  = require("BeaverStash.Table")

---@param boxes tts__ObjectState
local function handle(boxes)
    local BoxBox = --[[---@not nil]] Object.BoxBox:find()

    local BoxBoxData = --[[---@type tts__ContainerState ]] BoxBox.getData()

    Table.append(BoxBoxData.ContainedObjects, (--[[---@type tts__ContainerState ]]boxes).ContainedObjects)

    BoxBox.destruct()
    spawnObjectData({ data = BoxBoxData })
end

return handle